"use client";

import { useMemo, useState } from "react";
import type { AuditLog, AutomationRun, BankTransaction, CashflowPoint, CollectionEvent, Customer, FinancialAlert, Payable, Receivable, Supplier } from "@/lib/types";

type Section = "dashboard" | "receivables" | "payables" | "customers" | "suppliers" | "collections" | "cashflow" | "reconciliation" | "alerts" | "logs" | "automations";
type Dashboard = ReturnType<typeof import("@/lib/services").getDashboard>;
type Initial = { dashboard: Dashboard; cashflow: CashflowPoint[]; customers: Customer[]; suppliers: Supplier[]; receivables: Receivable[]; payables: Payable[]; bankTransactions: BankTransaction[]; collectionEvents: CollectionEvent[]; alerts: FinancialAlert[]; auditLogs: AuditLog[]; automationRuns: AutomationRun[] };

const menu: { id: Section; label: string; group: string }[] = [
  { id: "dashboard", label: "Visão geral", group: "Operação" }, { id: "receivables", label: "Contas a receber", group: "Operação" }, { id: "payables", label: "Contas a pagar", group: "Operação" }, { id: "cashflow", label: "Fluxo de caixa", group: "Operação" },
  { id: "customers", label: "Clientes", group: "Cadastros" }, { id: "suppliers", label: "Fornecedores", group: "Cadastros" },
  { id: "collections", label: "Régua de cobrança", group: "Automação" }, { id: "reconciliation", label: "Conciliação", group: "Automação" }, { id: "alerts", label: "Alertas", group: "Automação" }, { id: "automations", label: "Execuções", group: "Automação" }, { id: "logs", label: "Auditoria", group: "Governança" },
];
const titles: Record<Section, [string, string]> = {
  dashboard: ["Visão geral", "Acompanhe caixa, vencimentos e pontos de atenção."], receivables: ["Contas a receber", "Controle faturas, pagamentos e cobranças."], payables: ["Contas a pagar", "Aprove e acompanhe os compromissos financeiros."], customers: ["Clientes", "Carteira, risco e histórico financeiro."], suppliers: ["Fornecedores", "Custos recorrentes e relacionamento financeiro."], collections: ["Régua de cobrança", "Cadência automática simulada e histórico de contatos."], cashflow: ["Fluxo de caixa", "Projeção diária, semanal e mensal."], reconciliation: ["Conciliação bancária", "Sugestões de match e exceções do extrato."], alerts: ["Alertas financeiros", "Ocorrências priorizadas para tratamento."], logs: ["Logs e auditoria", "Rastreabilidade das ações do sistema."], automations: ["Automações", "Rotinas internas prontas para orquestração."],
};
const money = (value: number) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(value);
const date = (value: string) => new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "short", year: "numeric" }).format(new Date(value));
const dateTime = (value: string) => new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short" }).format(new Date(value));
const labelize = (value: string) => value.replaceAll("_", " ").toLowerCase().replace(/^./, (c) => c.toUpperCase());

export function FinanceOpsApp({ initial }: { initial: Initial }) {
  const [section, setSection] = useState<Section>("dashboard");
  const [search, setSearch] = useState(""); const [status, setStatus] = useState("ALL"); const [notice, setNotice] = useState("");
  const [receivables, setReceivables] = useState(initial.receivables); const [payables, setPayables] = useState(initial.payables);
  const [transactions, setTransactions] = useState(initial.bankTransactions); const [alerts, setAlerts] = useState(initial.alerts);
  const [collections, setCollections] = useState(initial.collectionEvents); const [runs, setRuns] = useState(initial.automationRuns);
  const showNotice = (text: string) => { setNotice(text); window.setTimeout(() => setNotice(""), 2600); };
  const request = async (url: string, options?: RequestInit) => { const response = await fetch(url, { ...options, headers: { "content-type": "application/json", ...options?.headers } }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error?.message ?? "Falha na operação"); return payload.data; };
  const mutateReceivable = async (id: string, action: "paid" | "collect") => { try { if (action === "paid") { const item = await request(`/api/receivables/${id}/status`, { method: "PATCH", body: JSON.stringify({ status: "PAID" }) }); setReceivables((items) => items.map((entry) => entry.id === id ? item : entry)); showNotice("Recebível marcado como pago."); } else { const event = await request(`/api/receivables/${id}/collection`, { method: "POST" }); if (!event.duplicate) setCollections((items) => [event, ...items]); showNotice(event.duplicate ? "Cobrança já simulada há menos de um minuto." : "Cobrança simulada e registrada."); } } catch (error) { showNotice((error as Error).message); } };
  const mutatePayable = async (id: string, nextStatus: "APPROVED" | "PAID") => { try { const item = await request(`/api/payables/${id}/status`, { method: "PATCH", body: JSON.stringify({ status: nextStatus }) }); setPayables((items) => items.map((entry) => entry.id === id ? item : entry)); showNotice(nextStatus === "APPROVED" ? "Pagamento aprovado." : "Conta marcada como paga."); } catch (error) { showNotice((error as Error).message); } };
  const reconcile = async (id: string, action: "confirm" | "ignore") => { const item = await request(`/api/bank-transactions/${id}/reconcile`, { method: "POST", body: JSON.stringify({ action }) }); setTransactions((items) => items.map((entry) => entry.id === id ? item : entry)); showNotice(action === "confirm" ? "Match confirmado." : "Transação ignorada."); };
  const resolve = async (id: string) => { const item = await request(`/api/alerts/${id}/resolve`, { method: "POST" }); setAlerts((items) => items.map((entry) => entry.id === id ? item : entry)); showNotice("Alerta resolvido."); };
  const run = async (name: string) => { const item = await request(`/api/automations/${name}/run`, { method: "POST" }); setRuns((items) => [item, ...items]); showNotice(`Automação ${name} concluída: ${item.summary}.`); };
  const [title, subtitle] = titles[section];
  const groupedMenu = [...new Set(menu.map((item) => item.group))];

  return <div className="app-shell">
    <aside className="sidebar">
      <div className="brand"><span className="brand-mark">F</span><div><strong>FinanceOps</strong><small>Automático</small></div></div>
      <div className="company-switch"><small>EMPRESA ATIVA</small><strong>{initial.dashboard.company.name}</strong><span>Ambiente demo</span></div>
      <nav>{groupedMenu.map((group) => <div key={group} className="nav-group"><small>{group}</small>{menu.filter((item) => item.group === group).map((item) => <button key={item.id} className={section === item.id ? "active" : ""} onClick={() => { setSection(item.id); setSearch(""); setStatus("ALL"); }}><span className="nav-dot" />{item.label}{item.id === "alerts" && <b>{alerts.filter((a) => a.status === "OPEN").length}</b>}</button>)}</div>)}</nav>
      <div className="sidebar-footer"><div className="avatar">AF</div><div><strong>Ana Admin</strong><span>Administrador</span></div><a href="/login">Trocar</a></div>
    </aside>
    <main className="main">
      <header className="topbar"><div><p className="eyebrow">OUTBOX TECH DEMO · ATUALIZADO AGORA</p><h1>{title}</h1><p>{subtitle}</p></div><div className="top-actions"><button className="icon-button" aria-label="Notificações">●</button><button className="primary" onClick={() => run("cashflow")}>Atualizar dados</button></div></header>
      <div className="content">
        {section === "dashboard" && <DashboardView data={initial.dashboard} />}
        {section === "receivables" && <ReceivablesView items={receivables} search={search} status={status} setSearch={setSearch} setStatus={setStatus} mutate={mutateReceivable} />}
        {section === "payables" && <PayablesView items={payables} search={search} status={status} setSearch={setSearch} setStatus={setStatus} mutate={mutatePayable} />}
        {section === "customers" && <CustomersView items={initial.customers} search={search} setSearch={setSearch} />}
        {section === "suppliers" && <SuppliersView items={initial.suppliers} search={search} setSearch={setSearch} />}
        {section === "collections" && <CollectionsView items={collections} receivables={receivables} mutate={mutateReceivable} />}
        {section === "cashflow" && <CashflowView points={initial.cashflow} threshold={initial.dashboard.company.lowCashThreshold} />}
        {section === "reconciliation" && <ReconciliationView items={transactions} status={status} setStatus={setStatus} reconcile={reconcile} />}
        {section === "alerts" && <AlertsView items={alerts} status={status} setStatus={setStatus} resolve={resolve} />}
        {section === "logs" && <LogsView audit={initial.auditLogs} runs={runs} />}
        {section === "automations" && <AutomationsView runs={runs} run={run} />}
      </div>
    </main>
    {notice && <div className="toast">{notice}</div>}
  </div>;
}

function DashboardView({ data }: { data: Dashboard }) {
  const kpis = [
    ["Saldo atual", data.kpis.currentBalance, "Conta operacional"], ["Projetado · 7 dias", data.kpis.projected7, "Entradas e saídas previstas"], ["Projetado · 30 dias", data.kpis.projected30, "Cenário base"], ["A receber no mês", data.kpis.receivableMonth, `${data.kpis.overdueCount} vencidas`], ["A pagar no mês", data.kpis.payableMonth, `${data.kpis.dueTodayCount} vencendo hoje`], ["Inadimplência", data.kpis.delinquency, "Requer acompanhamento"],
  ] as const;
  return <><section className="kpi-grid">{kpis.map(([label, value, hint], i) => <article className={`card kpi ${i === 5 ? "warning" : ""}`} key={label}><span>{label}</span><strong>{money(value)}</strong><small>{hint}</small></article>)}</section>
    <section className="split-grid wide-left"><article className="card"><SectionTitle title="Fluxo de caixa projetado" hint="Próximos 30 dias" /><BalanceChart points={data.cashflow} /></article><article className="card"><SectionTitle title="Alertas críticos" hint={`${data.criticalAlerts.length} em destaque`} />{data.criticalAlerts.map((item) => <div className="alert-row" key={item.id}><span className={`severity ${item.severity.toLowerCase()}`}>{item.severity}</span><div><strong>{item.type}</strong><small>{item.description}</small></div></div>)}</article></section>
    <section className="split-grid"><article className="card"><SectionTitle title="Principais clientes em atraso" hint="Por valor em aberto" /><RankedList items={data.topOverdueCustomers} /></article><article className="card"><SectionTitle title="Maiores despesas por categoria" hint="Mês atual" /><RankedList items={data.topExpenseCategories} /></article></section></>;
}

function BalanceChart({ points }: { points: CashflowPoint[] }) { const min = Math.min(...points.map((p) => p.projectedBalance)); const max = Math.max(...points.map((p) => p.projectedBalance)); return <div className="chart"><div className="chart-bars">{points.map((point, i) => <div key={point.date} className="chart-column" title={`${point.label}: ${money(point.projectedBalance)}`}><span style={{ height: `${22 + ((point.projectedBalance - min) / Math.max(max - min, 1)) * 70}%` }} /><small>{i % 5 === 0 ? point.label : ""}</small></div>)}</div><div className="chart-legend"><span>Menor projeção <b>{money(min)}</b></span><span>Maior projeção <b>{money(max)}</b></span></div></div>; }
function RankedList({ items }: { items: { name: string; amount: number }[] }) { const max = Math.max(...items.map((i) => i.amount), 1); return <div className="rank-list">{items.map((item, index) => <div className="rank" key={item.name}><span>{index + 1}</span><div><div><strong>{item.name}</strong><b>{money(item.amount)}</b></div><i><em style={{ width: `${(item.amount / max) * 100}%` }} /></i></div></div>)}</div>; }
function SectionTitle({ title, hint, action }: { title: string; hint?: string; action?: React.ReactNode }) { return <div className="section-title"><div><h2>{title}</h2>{hint && <p>{hint}</p>}</div>{action}</div>; }
function Filters({ search, status, setSearch, setStatus, placeholder = "Buscar..." }: { search: string; status: string; setSearch: (v: string) => void; setStatus: (v: string) => void; placeholder?: string }) { return <div className="filters"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder={placeholder} /><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="ALL">Todos os status</option><option value="PENDING">Pendente</option><option value="APPROVED">Aprovado</option><option value="PAID">Pago</option><option value="OVERDUE">Vencido</option></select></div>; }
function StatusBadge({ value }: { value: string }) { return <span className={`status status-${value.toLowerCase()}`}>{labelize(value)}</span>; }

function ReceivablesView({ items, search, status, setSearch, setStatus, mutate }: { items: Receivable[]; search: string; status: string; setSearch: (v: string) => void; setStatus: (v: string) => void; mutate: (id: string, action: "paid" | "collect") => void }) { const filtered = useMemo(() => items.filter((i) => (status === "ALL" || i.status === status) && `${i.customer} ${i.description}`.toLowerCase().includes(search.toLowerCase())), [items, search, status]); return <article className="card table-card"><SectionTitle title={`${filtered.length} recebíveis`} hint={`${money(filtered.reduce((t, i) => t + i.amount, 0))} no filtro atual`} action={<Filters {...{ search, status, setSearch, setStatus }} placeholder="Cliente ou descrição" />} /><div className="table-wrap"><table><thead><tr><th>Cliente / descrição</th><th>Vencimento</th><th>Status</th><th>Valor</th><th>Responsável</th><th>Ações</th></tr></thead><tbody>{filtered.slice(0, 60).map((item) => <tr key={item.id}><td><strong>{item.customer}</strong><small>{item.description} · {item.paymentMethod}</small></td><td>{date(item.dueDate)}</td><td><StatusBadge value={item.status} /></td><td className="money">{money(item.amount)}</td><td>{item.owner}</td><td className="actions"><button onClick={() => mutate(item.id, "collect")} disabled={item.status === "PAID"}>Cobrar</button><button onClick={() => mutate(item.id, "paid")} disabled={item.status === "PAID"}>Marcar pago</button></td></tr>)}</tbody></table></div></article>; }
function PayablesView({ items, search, status, setSearch, setStatus, mutate }: { items: Payable[]; search: string; status: string; setSearch: (v: string) => void; setStatus: (v: string) => void; mutate: (id: string, status: "APPROVED" | "PAID") => void }) { const filtered = items.filter((i) => (status === "ALL" || i.status === status) && `${i.supplier} ${i.description}`.toLowerCase().includes(search.toLowerCase())); return <article className="card table-card"><SectionTitle title={`${filtered.length} contas a pagar`} hint={`${money(filtered.reduce((t, i) => t + i.amount, 0))} no filtro atual`} action={<Filters {...{ search, status, setSearch, setStatus }} placeholder="Fornecedor ou descrição" />} /><div className="table-wrap"><table><thead><tr><th>Fornecedor / descrição</th><th>Vencimento</th><th>Categoria</th><th>Status</th><th>Valor</th><th>Ações</th></tr></thead><tbody>{filtered.slice(0, 60).map((item) => <tr className={item.amount > 20_000 ? "high-value" : ""} key={item.id}><td><strong>{item.supplier}</strong><small>{item.description} · {item.costCenter}</small></td><td>{date(item.dueDate)}</td><td>{item.category}</td><td><StatusBadge value={item.status} /></td><td className="money">{money(item.amount)}{item.amount > 20_000 && <small>Valor alto</small>}</td><td className="actions"><button onClick={() => mutate(item.id, "APPROVED")} disabled={item.status !== "PENDING"}>Aprovar</button><button onClick={() => mutate(item.id, "PAID")} disabled={item.status === "PAID"}>Pagar</button></td></tr>)}</tbody></table></div></article>; }
function CustomersView({ items, search, setSearch }: { items: Customer[]; search: string; setSearch: (v: string) => void }) { const filtered = items.filter((i) => `${i.name} ${i.document}`.toLowerCase().includes(search.toLowerCase())); return <><div className="filters standalone"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Buscar cliente" /></div><div className="entity-grid">{filtered.map((item) => <article className="card entity" key={item.id}><div><div className="entity-avatar">{item.name.split(" ").map((n) => n[0]).slice(0, 2).join("")}</div><span className={`risk risk-${item.riskScore > 70 ? "high" : item.riskScore > 50 ? "medium" : "low"}`}>Risco {item.riskScore}%</span></div><h3>{item.name}</h3><p>{item.document}</p><p>{item.email}</p><div className="entity-stats"><span><small>Em aberto</small><b>{money(item.totalOpen)}</b></span><span><small>Pago</small><b>{money(item.totalPaid)}</b></span><span><small>Faturas</small><b>{item.invoiceCount}</b></span></div><footer>{item.history}</footer></article>)}</div></>; }
function SuppliersView({ items, search, setSearch }: { items: Supplier[]; search: string; setSearch: (v: string) => void }) { const filtered = items.filter((i) => `${i.name} ${i.category}`.toLowerCase().includes(search.toLowerCase())); return <><div className="filters standalone"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Buscar fornecedor ou categoria" /></div><div className="entity-grid">{filtered.map((item) => <article className="card entity" key={item.id}><div><div className="entity-avatar supplier">{item.name.slice(0, 2).toUpperCase()}</div><span className="recurrence">{item.recurrence}</span></div><h3>{item.name}</h3><p>{item.document}</p><p>{item.category}</p><div className="entity-stats two"><span><small>Total pago</small><b>{money(item.totalPaid)}</b></span><span><small>Pendente</small><b>{money(item.totalPending)}</b></span></div><footer>{item.history}</footer></article>)}</div></>; }
function CollectionsView({ items, receivables, mutate }: { items: CollectionEvent[]; receivables: Receivable[]; mutate: (id: string, action: "paid" | "collect") => void }) { const overdue = receivables.filter((r) => r.status === "OVERDUE").slice(0, 8); return <><section className="rule-grid">{[[-3, "Lembrete amigável"], [0, "Aviso com link"], [2, "Aviso de atraso"], [7, "Cobrança firme"], [15, "Contato humano"]].map(([days, label]) => <article className="card rule" key={days}><strong>D{Number(days) >= 0 ? "+" : ""}{days}</strong><span>{label}</span><small>E-mail + WhatsApp simulado</small></article>)}</section><section className="split-grid wide-left"><article className="card table-card"><SectionTitle title="Histórico de cobrança" hint={`${items.length} eventos registrados`} /><div className="table-wrap compact"><table><thead><tr><th>Cliente / fatura</th><th>Canal</th><th>Status</th><th>Data</th><th>Automação</th></tr></thead><tbody>{items.slice(0, 30).map((item) => <tr key={item.id}><td><strong>{item.customer}</strong><small>{item.invoice}</small></td><td>{item.channel}</td><td><StatusBadge value={item.status === "Falhou" ? "FAILED" : "SUCCESS"} /></td><td>{dateTime(item.sentAt)}</td><td>{item.automation}</td></tr>)}</tbody></table></div></article><article className="card"><SectionTitle title="Aguardando contato" hint="Maiores atrasos" />{overdue.map((item) => <div className="queue-row" key={item.id}><div><strong>{item.customer}</strong><small>{money(item.amount)} · {date(item.dueDate)}</small></div><button onClick={() => mutate(item.id, "collect")}>Simular</button></div>)}</article></section></>; }
function CashflowView({ points, threshold }: { points: CashflowPoint[]; threshold: number }) {
  const weeks = Array.from({ length: 5 }, (_, index) => points.slice(index * 7, index * 7 + 7));
  const first = points[0];
  const cards: Array<[string, number, string]> = [
    ["Saldo inicial", first ? first.projectedBalance - first.expectedIn + first.expectedOut : 0, "Hoje"],
    ["Entradas previstas", points.reduce((total, point) => total + point.expectedIn, 0), "30 dias"],
    ["Saídas previstas", points.reduce((total, point) => total + point.expectedOut, 0), "30 dias"],
    ["Saldo final", points.at(-1)?.projectedBalance ?? 0, "Cenário base"],
  ];
  return <>
    <section className="kpi-grid four">{cards.map(([label, value, hint]) => <article className="card kpi" key={label}><span>{label}</span><strong>{money(value)}</strong><small>{hint}</small></article>)}</section>
    <article className="card"><SectionTitle title="Projeção diária" hint={`Limite de segurança: ${money(threshold)}`} /><BalanceChart points={points} /></article>
    <section className="week-grid">{weeks.map((week, index) => week.length ? <article className="card week" key={index}><small>SEMANA {index + 1}</small><strong>{money(week.at(-1)?.projectedBalance ?? 0)}</strong><span>+ {money(week.reduce((total, point) => total + point.expectedIn, 0))}</span><span>− {money(week.reduce((total, point) => total + point.expectedOut, 0))}</span></article> : null)}</section>
  </>;
}
function ReconciliationView({ items, status, setStatus, reconcile }: { items: BankTransaction[]; status: string; setStatus: (v: string) => void; reconcile: (id: string, action: "confirm" | "ignore") => void }) { const filtered = items.filter((i) => status === "ALL" || i.status === status); return <article className="card table-card"><SectionTitle title={`${filtered.length} transações bancárias`} hint={`${items.filter((i) => i.status === "MATCHED").length} conciliadas automaticamente`} action={<select value={status} onChange={(e) => setStatus(e.target.value)}><option value="ALL">Todos os resultados</option>{["MATCHED", "SUGGESTED", "DIVERGENT", "DUPLICATE", "UNIDENTIFIED", "IGNORED"].map((s) => <option key={s}>{s}</option>)}</select>} /><div className="table-wrap"><table><thead><tr><th>Transação</th><th>Data</th><th>Valor</th><th>Resultado</th><th>Sugestão</th><th>Ações</th></tr></thead><tbody>{filtered.slice(0, 70).map((item) => <tr key={item.id}><td><strong>{item.description}</strong><small>{item.externalId}</small></td><td>{date(item.postedAt)}</td><td className={`money ${item.direction.toLowerCase()}`}>{item.direction === "CREDIT" ? "+" : "−"} {money(item.amount)}</td><td><StatusBadge value={item.status} /></td><td>{item.suggestionLabel ? <><strong>{item.suggestionLabel}</strong><small>{item.confidence}% de confiança</small></> : "Sem identificação"}</td><td className="actions"><button disabled={!item.suggestionId || item.status === "MATCHED"} onClick={() => reconcile(item.id, "confirm")}>Confirmar</button><button disabled={item.status === "IGNORED"} onClick={() => reconcile(item.id, "ignore")}>Ignorar</button></td></tr>)}</tbody></table></div></article>; }
function AlertsView({ items, status, setStatus, resolve }: { items: FinancialAlert[]; status: string; setStatus: (v: string) => void; resolve: (id: string) => void }) { const filtered = items.filter((i) => status === "ALL" || i.status === status); return <article className="card table-card"><SectionTitle title={`${filtered.length} alertas`} hint={`${items.filter((i) => i.status === "OPEN").length} abertos`} action={<select value={status} onChange={(e) => setStatus(e.target.value)}><option value="ALL">Todos</option><option value="OPEN">Abertos</option><option value="RESOLVED">Resolvidos</option></select>} /><div className="alert-list">{filtered.map((item) => <div className="alert-item" key={item.id}><span className={`severity ${item.severity.toLowerCase()}`}>{item.severity}</span><div><strong>{item.type}</strong><p>{item.description}</p><small>{item.entityType} · {dateTime(item.createdAt)}</small></div><StatusBadge value={item.status} /><button onClick={() => resolve(item.id)} disabled={item.status === "RESOLVED"}>Resolver</button></div>)}</div></article>; }
function LogsView({ audit, runs }: { audit: AuditLog[]; runs: AutomationRun[] }) { const rows = [...audit.map((item) => ({ at: item.createdAt, action: item.action, entity: item.entityType, actor: item.actor, detail: item.metadata })), ...runs.map((item) => ({ at: item.startedAt, action: `AUTOMATION_${item.status}`, entity: item.name, actor: "Sistema", detail: item.summary }))].sort((a, b) => +new Date(b.at) - +new Date(a.at)); return <article className="card table-card"><SectionTitle title="Trilha de auditoria" hint={`${rows.length} eventos imutáveis na demonstração`} /><div className="table-wrap"><table><thead><tr><th>Data/hora</th><th>Ação</th><th>Entidade</th><th>Ator</th><th>Detalhe</th></tr></thead><tbody>{rows.slice(0, 70).map((item, i) => <tr key={`${item.at}-${i}`}><td>{dateTime(item.at)}</td><td><code>{item.action}</code></td><td>{item.entity}</td><td>{item.actor}</td><td>{item.detail}</td></tr>)}</tbody></table></div></article>; }
function AutomationsView({ runs, run }: { runs: AutomationRun[]; run: (name: string) => void }) { const automations = [{ name: "collection", title: "Cobrança automática", description: "Aplica a régua às faturas vencendo ou vencidas." }, { name: "alerts", title: "Alertas financeiros", description: "Detecta vencimentos, valores altos e exceções." }, { name: "cashflow", title: "Fluxo de caixa", description: "Recalcula a projeção financeira dos próximos 30 dias." }, { name: "reconciliation", title: "Conciliação", description: "Busca correspondências entre extrato e lançamentos." }]; return <><div className="automation-grid">{automations.map((item) => { const last = runs.find((r) => r.name === item.name); return <article className="card automation" key={item.name}><div className="automation-icon">↻</div><h3>{item.title}</h3><p>{item.description}</p><div><small>ÚLTIMA EXECUÇÃO</small><span>{last ? `${dateTime(last.startedAt)} · ${last.status}` : "Nunca"}</span></div><button className="primary" onClick={() => run(item.name)}>Executar agora</button></article>; })}</div><article className="card table-card"><SectionTitle title="Execuções recentes" hint="Histórico das rotinas internas" /><div className="table-wrap compact"><table><thead><tr><th>Automação</th><th>Início</th><th>Status</th><th>Processados</th><th>Resumo</th></tr></thead><tbody>{runs.slice(0, 30).map((item) => <tr key={item.id}><td><strong>{labelize(item.name)}</strong></td><td>{dateTime(item.startedAt)}</td><td><StatusBadge value={item.status} /></td><td>{item.processed}</td><td>{item.summary}</td></tr>)}</tbody></table></div></article></>; }
