"use client";
import { FormEvent, useState } from "react";

const accounts = ["admin@financeops.demo", "financeiro@financeops.demo", "aprovador@financeops.demo", "viewer@financeops.demo"];
export default function LoginPage() {
  const [email, setEmail] = useState(accounts[0]); const [password, setPassword] = useState("Demo@123"); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); const response = await fetch("/api/auth/login", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email, password }) }); const payload = await response.json(); setLoading(false); if (!response.ok) return setError(payload.error.message); window.location.href = "/"; }
  return <main className="login-page"><section className="login-copy"><div className="brand login-brand"><span className="brand-mark">F</span><div><strong>FinanceOps</strong><small>Automático</small></div></div><p className="eyebrow">AMBIENTE DE DEMONSTRAÇÃO</p><h1>Operação financeira organizada, previsível e rastreável.</h1><p>Centralize contas, caixa, cobrança, conciliação e alertas em uma base pronta para automações.</p><ul><li>Dados fictícios realistas em reais</li><li>Quatro perfis de acesso</li><li>Ações simuladas com auditoria</li></ul></section><section className="login-panel"><form onSubmit={submit} className="login-card"><h2>Acessar a demonstração</h2><p>Selecione um perfil e use a senha padrão.</p><label>Perfil demo<select value={email} onChange={(e) => setEmail(e.target.value)}>{accounts.map((account) => <option key={account}>{account}</option>)}</select></label><label>Senha<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} /></label>{error && <div className="login-error">{error}</div>}<button className="primary" disabled={loading}>{loading ? "Entrando..." : "Entrar no FinanceOps"}</button><small>Senha demo: <code>Demo@123</code></small></form></section></main>;
}
